version: '3.9'
services:
  api:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build: ./backend
    command: celery -A app.celery:celery_app worker --loglevel=info
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
